name: SoapServices
services:
  soap-service-1:
    image: soap-service-1-image:latest
    container_name: soap-service-1
    ports:
      - "8081:8080"
    environment:
      - SERVICE_NAME=Soap Service 1
    networks:
      - soap-network

  soap-service-2:
    image: soap-service-2-image:latest
    container_name: soap-service-2
    ports:
      - "8082:8080"
    environment:
      - SERVICE_NAME=Soap Service 2
    networks:
      - soap-network

networks:
  soap-network:
    driver: bridge
