name: SoapServices
services:
  broker:
    build: ./camel-broker/
    container_name: soap_camel_broker
    ports:
      - "8080:8080"
    networks:
      - soap-network

  billing-service:
    build: ./billing-service/
    container_name: soap_billing_service
    ports:
      - "8081:8080"
    networks:
      - soap-network

  inventory-service:
    build: ./inventory-service/
    container_name: soap_inventory_service
    ports:
      - "8082:8080"
    networks:
      - soap-network

  customer-service:
    build: ./customer-service/
    container_name: soap_customer_service
    ports:
      - "8083:8080"
    networks:
      - soap-network

networks:
  soap-network:
    driver: bridge
